# Generated by Django 4.2.4 on 2023-11-19 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_sub_categories_youtube_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcategoryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default='sub-category.jpg', upload_to='sub-categories-images')),
                ('date', models.DateField(auto_now_add=True)),
                ('sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sub_categories')),
            ],
            options={
                'verbose_name_plural': 'Sub Categories Images',
            },
        ),
    ]
