# Generated by Django 4.2.4 on 2023-12-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_subcategoryimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_categories',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sub_categories',
            name='meta_description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sub_categories',
            name='meta_tag',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sub_categories',
            name='meta_title',
            field=models.CharField(max_length=200),
        ),
    ]
