# Generated by Django 4.2.4 on 2023-12-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_sub_categories_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_categories',
            name='page_about_description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
