# Generated by Django 4.2.4 on 2023-12-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_sub_categories_page_about_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_categories',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
