# Generated by Django 4.2.4 on 2023-12-04 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_sub_categories_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_categories',
            name='slug',
        ),
    ]
