# Generated by Django 4.2.4 on 2023-12-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_remove_sub_categories_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_categories',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
