# Generated by Django 4.2.4 on 2023-12-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_sub_categories_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='canonical_link',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sub_categories',
            name='canonical_link',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
