# Generated by Django 4.2.4 on 2023-12-06 06:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_product_canonical_link_product_product_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_categories',
            name='bottom_page_description',
            field=ckeditor.fields.RichTextField(default=1, max_length=1500),
            preserve_default=False,
        ),
    ]
