# Generated by Django 4.2.4 on 2023-12-06 06:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_sub_categories_bottom_page_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bottom_page_description',
            field=ckeditor.fields.RichTextField(default=1, max_length=1500),
            preserve_default=False,
        ),
    ]
