# Generated by Django 4.2.4 on 2023-12-06 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_remove_sub_categories_canonical_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='canonical_link',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_tag',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_title',
        ),
        migrations.CreateModel(
            name='ProductSeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_link', models.CharField(max_length=200)),
                ('meta_description', models.CharField(max_length=200)),
                ('meta_title', models.CharField(max_length=200)),
                ('meta_tag', models.CharField(max_length=200)),
                ('meta_robots', models.CharField(max_length=100)),
                ('og_url', models.CharField(max_length=100)),
                ('og_title', models.CharField(max_length=100)),
                ('og_description', models.CharField(max_length=100)),
                ('og_image', models.CharField(max_length=100)),
                ('twitter_title', models.CharField(max_length=100)),
                ('twitter_description', models.CharField(max_length=100)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product')),
            ],
            options={
                'verbose_name_plural': 'Product Seo',
            },
        ),
    ]
