# Generated by Django 4.2.4 on 2023-12-08 06:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_remove_product_canonical_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_categories',
            name='bottom_page_description',
            field=ckeditor.fields.RichTextField(max_length=35000),
        ),
    ]
