# Generated by Django 4.2.4 on 2023-12-11 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_product_canonical_link_product_meta_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvarient',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='productvarient',
            name='meta_tag',
        ),
        migrations.RemoveField(
            model_name='productvarient',
            name='meta_title',
        ),
    ]
