# Generated by Django 4.2.4 on 2023-12-13 10:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_alter_product_bottom_page_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bottom_page_description',
            field=ckeditor.fields.RichTextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='sub_categories',
            name='bottom_page_description',
            field=ckeditor.fields.RichTextField(max_length=35000),
        ),
    ]
