# Generated by Django 4.2.4 on 2023-12-13 10:49

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_alter_product_bottom_page_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bottom_page_description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='sub_categories',
            name='bottom_page_description',
            field=tinymce.models.HTMLField(),
        ),
    ]
