# Generated by Django 4.2.4 on 2023-12-20 13:13

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_alter_product_bottom_page_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_policy_content', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name_plural': 'Privacy Policy',
            },
        ),
    ]
