# Generated by Django 4.2.4 on 2023-12-21 05:42

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_privacypolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_image', models.ImageField(default='blogs.jpg', upload_to='blogs-images')),
                ('blog_description', tinymce.models.HTMLField()),
                ('blog_tags', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
