# Generated by Django 4.2.4 on 2024-02-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_blogs_blog_slug_blogs_canonical_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_for_architect',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_for_importers',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_for_user',
        ),
        migrations.AlterField(
            model_name='product',
            name='canonical_link',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_robots',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_tag',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_title',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='og_description',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='og_image',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='og_title',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='og_url',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='twitter_description',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='twitter_title',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
