# Generated by Django 4.2.4 on 2024-02-04 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_remove_product_discount_for_architect_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='best_deal',
        ),
        migrations.RemoveField(
            model_name='product',
            name='best_seller',
        ),
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
