# Generated by Django 4.2.4 on 2024-02-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_remove_product_best_deal_remove_product_best_seller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='best_deal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='best_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='digital',
            field=models.BooleanField(default=False),
        ),
    ]
