# Generated by Django 4.2.4 on 2024-02-06 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0079_product_best_deal_product_best_seller_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="user",),
    ]
