# Generated by Django 4.2.4 on 2024-02-06 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0080_remove_product_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="best_deal",),
        migrations.RemoveField(model_name="product", name="best_seller",),
        migrations.RemoveField(model_name="product", name="digital",),
    ]
