# Generated by Django 4.2.4 on 2024-02-06 09:27

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0081_remove_product_best_deal_remove_product_best_seller_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="bottom_page_description",
            field=tinymce.models.HTMLField(default="N/A"),
        ),
    ]
