# Generated by Django 4.2.4 on 2024-02-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0082_alter_product_bottom_page_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="specifications",
            field=models.TextField(blank=True, default="N/A", null=True),
        ),
    ]
