# Generated by Django 4.2.4 on 2024-02-06 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0085_product_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="updated",),
    ]
