# Generated by Django 4.2.4 on 2024-02-14 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0092_productvarient_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="old_price",
            field=models.DecimalField(decimal_places=2, default="2", max_digits=9999),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default="1", max_digits=9999),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(default="Mobile & Laptop", max_length=500),
        ),
        migrations.AlterField(
            model_name="productvariantimages",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="productvarient",
            name="title",
            field=models.CharField(default="Product Varient", max_length=500),
        ),
    ]
