# Generated by Django 4.2.4 on 2024-03-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0095_remove_architectureimages_architecture_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="application",
            field=models.CharField(default="starter/seed", max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="hsn_code",
            field=models.CharField(default="5305", max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="material",
            field=models.CharField(default="Cocopith", max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="minimum_order_qty",
            field=models.CharField(default="1", max_length=500),
        ),
        migrations.AddField(
            model_name="product",
            name="packing_size",
            field=models.CharField(default="Box 100 Pcs", max_length=500),
        ),
        migrations.AddField(
            model_name="product",
            name="unit_item",
            field=models.CharField(default="BOX", max_length=100),
        ),
    ]
