# Generated by Django 4.2.4 on 2024-03-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0097_alter_product_sku"),
    ]

    operations = [
        migrations.RemoveField(model_name="main_category", name="icon_img",),
        migrations.AddField(
            model_name="main_category",
            name="banner_image",
            field=models.ImageField(
                default="maincategorybanner.jpg", upload_to="category"
            ),
        ),
        migrations.AddField(
            model_name="main_category",
            name="description",
            field=models.CharField(default="N/A", max_length=100),
        ),
        migrations.AlterField(
            model_name="main_category",
            name="meta_description",
            field=models.CharField(default="N/A", max_length=100),
        ),
        migrations.AlterField(
            model_name="main_category",
            name="meta_tag",
            field=models.CharField(default="N/A", max_length=100),
        ),
        migrations.AlterField(
            model_name="main_category",
            name="meta_title",
            field=models.CharField(default="N/A", max_length=100),
        ),
    ]
