# Generated by Django 4.2.4 on 2024-03-15 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0099_alter_main_category_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productvarient", old_name="pid", new_name="pvid",
        ),
        migrations.RemoveField(model_name="product", name="bottom_page_description",),
        migrations.RemoveField(model_name="product", name="color",),
        migrations.RemoveField(model_name="productvarient", name="color",),
        migrations.RemoveField(model_name="productvarient", name="date",),
        migrations.RemoveField(model_name="productvarient", name="image",),
        migrations.RemoveField(model_name="productvarient", name="old_price",),
        migrations.RemoveField(model_name="productvarient", name="price",),
        migrations.RemoveField(model_name="productvarient", name="product_status",),
        migrations.RemoveField(model_name="productvarient", name="specifications",),
        migrations.RemoveField(model_name="productvarient", name="user",),
    ]
