# Generated by Django 4.2.4 on 2024-03-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0101_productvarianttypes_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="cartorder", name="paid_status",),
        migrations.RemoveField(model_name="cartorder", name="user",),
        migrations.AddField(
            model_name="cartorder",
            name="razor_pay_order_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="razor_pay_payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="razor_pay_payment_signature",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default="1.99", max_digits=9999
            ),
        ),
    ]
