# Generated by Django 4.2.4 on 2024-03-21 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0102_remove_cartorder_paid_status_remove_cartorder_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="cartorder", name="razor_pay_order_id",),
        migrations.RemoveField(model_name="cartorder", name="razor_pay_payment_id",),
        migrations.RemoveField(
            model_name="cartorder", name="razor_pay_payment_signature",
        ),
        migrations.AddField(
            model_name="cartorder",
            name="paid_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="price",
            field=models.DecimalField(decimal_places=2, default="1", max_digits=99999),
        ),
        migrations.AlterField(
            model_name="cartorderitems",
            name="price",
            field=models.DecimalField(decimal_places=2, default="1", max_digits=99999),
        ),
        migrations.AlterField(
            model_name="cartorderitems",
            name="total",
            field=models.DecimalField(decimal_places=2, default="1", max_digits=99999),
        ),
    ]
