# Generated by Django 4.2.4 on 2024-03-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0104_product_gst_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="deal_of_week",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="new_arrival",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="summer_sale",
            field=models.BooleanField(default=False),
        ),
    ]
