# Generated by Django 4.2.4 on 2024-03-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0106_productvarient_gst_rate"),
    ]

    operations = [
        migrations.RemoveField(model_name="productvarient", name="gst_rate",),
        migrations.AddField(
            model_name="productvarianttypes",
            name="gst_rate",
            field=models.CharField(default="5%", max_length=12),
        ),
    ]
