# Generated by Django 4.2.4 on 2024-03-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0108_main_category_active_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="main_category",
            name="active_status",
            field=models.CharField(
                choices=[("disabled", "Disabled"), ("published", "Published")],
                default="disabled",
                max_length=10,
            ),
        ),
    ]
