# Generated by Django 4.2.4 on 2024-04-05 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0111_alter_productvarianttypes_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVariation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "variation_title",
                    models.CharField(default="Product Variation", max_length=500),
                ),
                ("status", models.BooleanField(default=True)),
                ("in_stock", models.BooleanField(default=True)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.product",
                    ),
                ),
                (
                    "product_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.productvarient",
                    ),
                ),
                (
                    "product_variant_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.productvarianttypes",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Product Variation",},
        ),
        migrations.CreateModel(
            name="ProductVariationTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "variation_type_title",
                    models.CharField(default="Product Variation", max_length=500),
                ),
                (
                    "varient_type_price",
                    models.DecimalField(decimal_places=2, default="1", max_digits=9999),
                ),
                ("gst_rate", models.CharField(default="5%", max_length=12)),
                ("status", models.BooleanField(default=True)),
                ("in_stock", models.BooleanField(default=True)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.product",
                    ),
                ),
                (
                    "product_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.productvarient",
                    ),
                ),
                (
                    "product_variant_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.productvarianttypes",
                    ),
                ),
                (
                    "product_variation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.productvariation",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Product Variation Types",},
        ),
    ]
