# Generated by Django 4.2.4 on 2024-04-05 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0112_productvariation_productvariationtypes"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="category",),
        migrations.DeleteModel(name="Category",),
    ]
