# Generated by Django 4.2.4 on 2024-04-05 06:46

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0113_remove_product_category_delete_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefgh12345",
                        length=22,
                        max_length=30,
                        prefix="cat",
                        unique=True,
                    ),
                ),
                (
                    "cat_title",
                    models.CharField(default="Mobile & Laptop", max_length=100),
                ),
                ("meta_description", models.CharField(max_length=100)),
                ("meta_title", models.CharField(max_length=100)),
                ("meta_tag", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(
                        default="category.jpg",
                        upload_to=core.models.user_directory_path,
                    ),
                ),
                (
                    "big_image",
                    models.ImageField(
                        default="bigcategory.jpg",
                        upload_to=core.models.user_directory_path,
                    ),
                ),
                (
                    "main_category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.main_category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name_plural": "Categories",},
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.category",
            ),
        ),
    ]
