# Generated by Django 4.2.4 on 2024-04-05 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0114_category_product_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariationtypes", name="varient_type_price",
        ),
    ]
