# Generated by Django 4.2.4 on 2024-04-07 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0116_productvariationtypes_varient_type_price_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productvariationtypes",
            old_name="variation_type_title",
            new_name="variation_title",
        ),
        migrations.RemoveField(
            model_name="productvariation", name="product_variant_type",
        ),
        migrations.RemoveField(model_name="productvariationtypes", name="gst_rate",),
        migrations.RemoveField(
            model_name="productvariationtypes", name="product_variant",
        ),
        migrations.RemoveField(
            model_name="productvariationtypes", name="product_variant_type",
        ),
        migrations.RemoveField(
            model_name="productvariationtypes", name="varient_type_price",
        ),
        migrations.AlterField(
            model_name="productvariationtypes",
            name="product_variation",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.productvariation",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ProductVariationTypesPrices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "varient_type_price",
                    models.DecimalField(decimal_places=2, default="1", max_digits=9999),
                ),
                ("gst_rate", models.CharField(default="5%", max_length=12)),
                ("status", models.BooleanField(default=True)),
                ("in_stock", models.BooleanField(default=True)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.product",
                    ),
                ),
                (
                    "product_variant_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.productvarianttypes",
                    ),
                ),
                (
                    "product_variation_types",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.productvariationtypes",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Product Variation Types Prices",},
        ),
    ]
