# Generated by Django 4.2.4 on 2024-04-08 07:26

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0117_rename_variation_type_title_productvariationtypes_variation_title_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="productvariation", name="in_stock",),
        migrations.AddField(
            model_name="productvariation",
            name="product_variant_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.productvarianttypes",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productvariationtypesprices",
            name="product_variation",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.productvariation",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="12345678900",
                length=22,
                max_length=25,
                prefix="sku",
                unique=True,
            ),
        ),
    ]
