# Generated by Django 4.2.4 on 2024-04-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0118_remove_productvariation_in_stock_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VariantTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="productvariation", name="product_variant_type",
        ),
        migrations.RemoveField(
            model_name="productvariationtypesprices", name="product_variation",
        ),
        migrations.AddField(
            model_name="product",
            name="variant_titles",
            field=models.ManyToManyField(
                related_name="products", to="core.varianttitle"
            ),
        ),
    ]
