# Generated by Django 4.2.4 on 2024-04-15 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0119_varianttitle_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="variant_titles",),
        migrations.DeleteModel(name="VariantTitle",),
    ]
