# Generated by Django 4.2.4 on 2024-04-15 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0120_remove_product_variant_titles_delete_varianttitle"),
    ]

    operations = [
        migrations.RemoveField(model_name="blogs", name="blog_tags",),
        migrations.RemoveField(model_name="blogs", name="canonical_link",),
        migrations.RemoveField(model_name="blogs", name="meta_description",),
        migrations.RemoveField(model_name="blogs", name="meta_robots",),
        migrations.RemoveField(model_name="blogs", name="meta_tag",),
        migrations.RemoveField(model_name="blogs", name="meta_title",),
        migrations.RemoveField(model_name="blogs", name="og_description",),
        migrations.RemoveField(model_name="blogs", name="og_image",),
        migrations.RemoveField(model_name="blogs", name="og_title",),
        migrations.RemoveField(model_name="blogs", name="og_url",),
        migrations.RemoveField(model_name="blogs", name="twitter_description",),
        migrations.RemoveField(model_name="blogs", name="twitter_title",),
    ]
