# Generated by Django 4.2.4 on 2024-04-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0122_testimonials"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonials",
            name="testimonial_company",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
