# Generated by Django 4.2.4 on 2024-06-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0124_alter_cartorder_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_status",
            field=models.CharField(
                choices=[("disabled", "Disabled"), ("published", "Published")],
                default="published",
                max_length=10,
            ),
        ),
    ]
