# Generated by Django 4.2.4 on 2024-06-17 05:22

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0125_alter_product_product_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="12345678900",
                length=22,
                max_length=7,
                prefix="sku",
                unique=True,
            ),
        ),
    ]
