# Generated by Django 4.2.4 on 2024-06-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0126_alter_product_sku"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="maximum_order_qty",
            field=models.CharField(default="1", max_length=500),
        ),
    ]
